name: custom_shape_painter
description: A Flutter package for drawing and erasing on masked shapes with coverage tracking
version: 0.0.1
homepage: https://github.com/kevinmathew94/custom_shape_painter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
